export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

// workout Actions
export const LOAD_WORKOUTS_SUCCESS = 'LOAD_WORKOUTS_SUCCESS';
export const CREATE_WORKOUT_SUCCESS = 'CREATE_WORKOUT_SUCCESS';
export const DELETE_WORKOUT_SUCCESS = 'DELETE_WORKOUT_SUCCESS';
export const UPDATE_WORKOUT_SUCCESS = 'UPDATE_WORKOUT_SUCCESS';
export const SCHEDULE_WORKOUT_SUCCESS = 'SCHEDULE_WORKOUT_SUCCESS';

export const LOAD_ACTIVITIES_SUCCESS = 'LOAD_ACTIVITIES_SUCCESS';

// ajax actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
